# Generated by Django 6.0.1 on 2026-01-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module', to='instructor.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vedio', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('module_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='instructor.module')),
            ],
        ),
    ]
