# Generated by Django 6.0.1 on 2026-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
